### ISSUE TITLE
执行react-native run-android，项目打包安装成功后，首次启动后闪退，再次点击又能启动

### ISSUE THREAD

**Issue by danna88** [listenzz/hybrid-navigation#130]
出现了如上所述的问题，无法通过命令自启动了，请问是什么原因呢？

**Comment by listenzz** [comment]
没遇到呢

**Comment by danna88** [comment]
> 没遇到呢，是使用本库遇到的吗？

对，一个新项目，只引用本库和UI库，啥都没得，大概率通过命令启动会闪退，再点就启动成功了，debug包

**Comment by listenzz** [comment]
我创建了个项目，和本库集成

https://github.com/listenzz/react-native-navigation-hybrid-rn60

我在模拟器上运行，没发现上述情况。

**Comment by danna88** [comment]
> 我创建了个项目，和本库集成
> 
> https://github.com/listenzz/react-native-navigation-hybrid-rn60
> 
> 我在模拟器上运行，没发现上述情况。

那就先不管吧，反正手动点也能启动。
