### ISSUE TITLE
内存增长问题

### ISSUE THREAD

**Issue by hiXgb** [listenzz/hybrid-navigation#132]
每次push一个页面都会重新初始化一个RCTRootView，内存会增长40MB左右，这个有什么方式可以优化吗？

**Comment by hiXgb** [comment]
我们工程的js文件较大，用你提供的Demo也会有这个现象，push RN 页面内存会不断增长

**Comment by listenzz** [comment]
有这么夸张吗？我的 demo push 上百个都没问题。
