### ISSUE TITLE
TopBar Button Actions

### ISSUE THREAD

**Issue by 8BallBomBom** [listenzz/hybrid-navigation#135]
From what it seems, if you push a screen and set actions on the left or right buttons at the same time then the actions don't actually work.

The actions only seem to work if you set them in the component directly.
At least this is what i've observed.

**Comment by listenzz** [comment]
Yes, you are right.

**Comment by 8BallBomBom** [comment]
Any plans on a fix so you can set them before the screen is pushed?
Or do we need to just set them in each screen directly?
