### ISSUE TITLE
是不是xcode11, ios13无法运行

### ISSUE THREAD

**Issue by padphp** [listenzz/hybrid-navigation#142]
2019-10-21 16:09:39.624681+0800 hello[490:33195] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'

**Comment by padphp** [comment]
react native 0.59.10

**Comment by padphp** [comment]
react-native-navigation-hybrid 0.16.9

**Comment by listenzz** [comment]
是的，不过不影响 release 版本，不打算升级到 react native 0.60+ 吗？

**Comment by padphp** [comment]
(void)hbd_setStatusBarHidden:(BOOL)hidden forViewController:(UIViewController *)vc {
要是不使用控制状态栏显示，是不是这个函数可以直接return。我试了一下，直接return就可以了。

**Comment by listenzz** [comment]
是的

**Comment by padphp** [comment]
我试了release版本还是会闪退，0.60+的版本没有这个问题吗？可以的话，我就尝试升级到0.60。

**Comment by padphp** [comment]
主要是0.60+有些开源组件还不兼容，还是59的稳定一些，之前尝试过升级，后来放弃了。

**Comment by listenzz** [comment]
待会我发个补丁

**Comment by padphp** [comment]
非常感谢

**Comment by listenzz** [comment]
试下 0.16.10

**Comment by padphp** [comment]
我怎么看到的16.10代码没有变化，还是

**Comment by padphp** [comment]
UIView *statusBar = [[UIApplication sharedApplication] valueForKey:@"statusBarWindow"];

**Comment by listenzz** [comment]
能 build 成功就对了

**Comment by padphp** [comment]
Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_HBDPopAnimation

Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_HBDPushAnimation

**Comment by listenzz** [comment]
知道了，我处理下，你是用 link 的方式引入的吧

**Comment by padphp** [comment]
对的

**Comment by listenzz** [comment]
再试试 0.16.11

**Comment by padphp** [comment]
可以了。非常感谢。你为什么不留一个Donation入口，我觉得你这个项目比react-native-navigation和react-navigation好用多了，简单易用，接地气，特别是async返回值，能解决好多以前RN开发回调难受的问题。

**Comment by padphp** [comment]
我还有个问题endRegisterComponent之后，还可以调用registerComponent不？

**Comment by listenzz** [comment]
被限制了

**Comment by neverleo** [comment]
"react-native": "^0.59.10",
"react-native-navigation-hybrid": "^0.20.0",
Xcode 11, iOS 13
编译报错：
Undefined symbol: _OBJC_CLASS_$_HBDPopAnimation
Undefined symbol: _OBJC_CLASS_$_HBDPushAnimation

请问如何解决？谢谢

**Comment by listenzz** [comment]
@neverleo 是使用 cocoapods 引入的吗？

**Comment by neverleo** [comment]
> @neverleo 是使用 cocoapods 引入的吗？

没有使用cocoapods

**Comment by listenzz** [comment]
@neverleo 刚刚看了下文档，rn 0.59 需要使用 0.16.14 版本
