### ISSUE TITLE
报了一个错，没找到怎么触发的

### ISSUE THREAD

**Issue by danna88** [listenzz/hybrid-navigation#147]
截图：
![Screenshot_20191107-155926](https://user-images.githubusercontent.com/6461710/68370925-865a7580-0178-11ea-83dd-0bacf94c1795.jpg)

大概是这样，我在登录过期后，使用Navigator.setRoot回到了Login页面，Navigator.setRoot里面只有一个Login，结果就报错了，然后我reload，在APP的启动过程中会使用Navigator.setRoot来到A页面，这次Navigator.setRoot只有A，点击A页面的按钮，会通过navigator.replaceToRoot来到Login页面，还是报这个。

**Comment by listenzz** [comment]
可以提供一个能复现此问题的 demo 吗。这貌似和 InputText 有关，react-native 有相关 issue

**Comment by danna88** [comment]
好，我试试能不能复现吧

**Comment by danna88** [comment]
死活重现不到了，只好后面遇到再说了。
