### ISSUE TITLE
await this.props.navigator.showModal()无法拿到值

### ISSUE THREAD

**Issue by danna88** [listenzz/hybrid-navigation#148]
async test() {
    const test = await props.navigator.showModal(routesName.CustomAlert, ALERT_EXPIRED_TIP, {
      dialogContent: 'test',
      requestCode: ALERT_EXPIRED_TIP
    });
    alert(3)
  }

上述方法，执行之后，alert(3)都没有执行，更无法获取结果，我看文档上是这么描述的，不知道错在哪儿了

**Comment by listenzz** [comment]
要等 modal 关闭后， alert(3) 才会执行。

CustomAlert 这个页面，需要调用 

```js
// 设置要返回的结果
this.props.navigator.setResult();
// 关闭 modal
this.props.navigator.hideModal();
```

**Comment by danna88** [comment]
我调用了的
this.props.navigator.setResult(this.props.requestCode);
this.props.navigator.hideModal();

**Comment by listenzz** [comment]
返回值是个元组，根据你的使用情况

` test[0] === ALERT_EXPIRED_TIP`

**Comment by danna88** [comment]
现在问题是，我通过三种拿返回值的方式，都无法拿到值，await props.navigator.showModal后面的代码也不会执行
但我试了，通过push的方式，pop之后可以在onComponentResult拿到返回值
