### ISSUE TITLE
modal无法再push一个新页面吗

### ISSUE THREAD

**Issue by YangfanY** [listenzz/hybrid-navigation#160]

**Comment by listenzz** [comment]
不能。 push 是 stack 的能力， 通过 showModal 显示的页面，没有嵌套在 stack 中。
可以通过 showModalLayout 来提供 push 的能力。

```js
const modalStack = {
  stack: {
    children: [{ screen: { moduleName: 'Modal' } }],
  },
}

showModalLayout(modalStack, 1)
```

**Comment by YangfanY** [comment]
> 不能。 push 是 stack 的能力， 通过 showModal 显示的页面，没有嵌套在 stack 中。
> 可以通过 showModalLayout 来提供 push 的能力。
> 
> ```js
> const modalStack = {
>   stack: {
>     children: [{ screen: { moduleName: 'Modal' } }],
>   },
> }
> 
> showModalLayout(modalStack, 1)
> ```

好的,我试下

**Comment by YangfanY** [comment]
请问 modalStack 是在页面里面配置还是在index.js里面写好呢

**Comment by listenzz** [comment]
@YangfanY 在调用 showModalLayout 的附近

**Comment by YangfanY** [comment]
(this.props as any).navigator.showModalLayout('AgreementModal', 1)会报错


ExceptionsManager.js:126 Exception '-[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x6000013a2920' was thrown while invoking dispatch on target NavigationHybrid with params (
    "A42658F7-88C6-465C-878A-01A6CD6676D5",
    showModalLayout,
        {
        layout = AgreementModal;
        requestCode = 1;
    }
)

**Comment by listenzz** [comment]
```js
(this.props as any).navigator.showModalLayout({
  stack: {
    children: [{ screen: { moduleName: 'AgreementModal' } }],
  },
}, 1)
```

**Comment by YangfanY** [comment]
> ```js
> (this.props as any).navigator.showModalLayout({
>   stack: {
>     children: [{ screen: { moduleName: 'AgreementModal' } }],
>   },
> }, 1)
> ```

可以了,但是这不是我想要的效果😂,这个直接跳一个新页面了,我想要做一个隐私协议的弹窗,然后可以点击文字跳转具体协议页面...

**Comment by listenzz** [comment]
@YangfanY 要关掉 modal 才可以跳

我们一般这么做：
```js
// 登录页面
const [resultCode, data] = await this.props.navigator.showModal('AgreementModal', 1)
if (resultCode === RESULT_OK) {
  this.props.navigator.push('具体协议')
}

//  AgreementModal 页面 
// 点击确定按钮
this.props.navigator.setResult(RESULT_OK, null)
this.props.navigator.hideModal()
```

**Comment by YangfanY** [comment]
> @YangfanY 要关掉 modal 才可以跳
> 
> 我们一般这么做：
> 
> ```js
> // 登录页面
> const [resultCode, data] = await this.props.navigator.showModal('AgreementModal', 1)
> if (resultCode === RESULT_OK) {
>   this.props.navigator.push('具体协议')
> }
> 
> //  AgreementModal 页面 
> // 点击确定按钮
> this.props.navigator.setResult(RESULT_OK, null)
> this.props.navigator.hideModal()
> ```

那我就这么做吧😂 麻烦了

**Comment by danna88** [comment]
请问你按照他的做法，能拿到返回值吗？就是const [resultCode, data] 这个能拿到吗？

**Comment by YangfanY** [comment]
> 请问你按照他的做法，能拿到返回值吗？就是const [resultCode, data] 这个能拿到吗？

我用的是onComponentResult这个钩子,可以拿到的,你在modal里面有setResult吗

**Comment by danna88** [comment]
> > 请问你按照他的做法，能拿到返回值吗？就是const [resultCode, data] 这个能拿到吗？
> 
> 我用的是onComponentResult这个钩子,可以拿到的,你在modal里面有setResult吗

有设置，但是就是没法取到值，用三种方式都无法取到值。
你的Modal页面是一个普通的react screen吗？

**Comment by danna88** [comment]
@listenzz 我新建了一个demo，可以拿到结果，但是在我项目中就不行，会不会是因为项目引入了redux的原因？ 不过我需要showModal的页面并没有用redux。
