### ISSUE TITLE
导航拦截器重定向时报错 :  Can't find target scene for action:push, maybe the scene is gone.

### ISSUE THREAD

**Issue by YangfanY** [listenzz/hybrid-navigation#162]

**Comment by listenzz** [comment]
操作步骤，或 demo？

使用 react-native-create-app 可以快速创建一个和本库集成的 demo

**Comment by YangfanY** [comment]
![image](https://user-images.githubusercontent.com/31607682/75147985-82f3f580-5739-11ea-9fec-e951ea31f482.png)
就是很简单的登陆判断 然后重定向

**Comment by listenzz** [comment]
你获取 navigator 的姿势可能不对，extras 里面应该有个叫 sceneId 的参数，使用它来获取 navigator

**Comment by YangfanY** [comment]
> 你获取 navigator 的姿势可能不对，extras 里面应该有个叫 sceneId 的参数，使用它来获取 navigator

我是const navigator = new Navigator() 这样获取的, 不可以吗...

**Comment by listenzz** [comment]
@YangfanY 使用 const navigator = Navigator.get(extras.sceneId)

**Comment by YangfanY** [comment]
> @YangfanY 使用 const navigator = Navigator.get(extras.sceneId)

好的 我试一下
