### ISSUE TITLE
请问tab上加个气泡按钮的效果能实现吗？

### ISSUE THREAD

**Issue by danna88** [listenzz/hybrid-navigation#163]
类似这种
![image](https://user-images.githubusercontent.com/6461710/77748554-855cae80-705b-11ea-8499-ebcac8f409a7.png)

点击气泡，到扫码界面，能提供下思路吗？

**Comment by listenzz** [comment]
demo 有示范

**Comment by danna88** [comment]
感谢，刚才试了下，可以实现那个效果，但是我发现，用自定义tab，切换tab的时候会有一闪一闪的问题

**Comment by listenzz** [comment]
可能是重新渲染了，可以考了做些优化

**Comment by danna88** [comment]
还有个严重问题是，tab会被键盘或者toast提示顶上去 = =！

**Comment by listenzz** [comment]
Android ? 截个图来看看

**Comment by danna88** [comment]
![Screenshot_20200401-131011](https://user-images.githubusercontent.com/6461710/78101658-c74e7180-741a-11ea-8d91-d8894698795c.jpg)
![Screenshot_20200401-130959](https://user-images.githubusercontent.com/6461710/78101667-cc132580-741a-11ea-9b85-b05b927442de.jpg)

**Comment by danna88** [comment]
![image](https://user-images.githubusercontent.com/6461710/78101695-ee0ca800-741a-11ea-9b71-c77d3e4973d6.png)
![image](https://user-images.githubusercontent.com/6461710/78101710-fb299700-741a-11ea-999c-bc895e3ef63c.png)

**Comment by danna88** [comment]
我这图片看不到上传成功没有，好像挂掉了

**Comment by danna88** [comment]
![image](https://user-images.githubusercontent.com/6461710/78101811-3b891500-741b-11ea-9d29-44415a548bf8.png)

**Comment by danna88** [comment]
我发到你邮箱了，这里上传不成功

**Comment by listenzz** [comment]
被键盘顶上去的，需要调整 Android 原生代码

```diff
// MainActivity.js
+ import android.view.WindowManager;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
+      getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
    }

```

**Comment by danna88** [comment]
好的，我试试，这个甚至会被黄屏信息弹上去

**Comment by danna88** [comment]
被键盘弹上去的解决了，感谢。其他的情况依然存在。

**Comment by listenzz** [comment]
被 toast 顶上去的，需要调整 toast 引入方式。

大多数的 toast 改写了 `AppRegistry.registerComponent` 的实现，在我们的页面之外包裹了一层，通过订阅的方式弹出 toast，本库是个多页应用，所以，不管在哪个页面弹出 toast , 都会在所有页面显示，自定义的 tabBar 本质也是个页面，所以在其它页面弹出的 toast 也会在 tabBar 上显示，因此把 tabBar 顶上去了。

**Comment by listenzz** [comment]
黄屏那个和 toast 类似，release 包是没有黄屏的，不碍事。

**Comment by listenzz** [comment]
toast 用的是那个库？

**Comment by danna88** [comment]
你的库不会有问题，但是由于没法改位置，所以用的是react-native-root-toast

**Comment by listenzz** [comment]
react-native-root-toast 依赖了 react-native-root-siblings

siblings 通过这行代码包裹了我们的页面  https://github.com/magicismight/react-native-root-siblings/blob/master/src/RootSiblingsManager.tsx#L19 

可以考虑关闭 siblings 自动包裹的功能，通过本库 ReactRegistry.startRegisterComponent 来包裹 siblings 提供的能力，

**Comment by danna88** [comment]
好，我研究一下多！

**Comment by danna88** [comment]
> 被键盘顶上去的，需要调整 Android 原生代码
> 
> ```diff
> // MainActivity.js
> + import android.view.WindowManager;
> 
> public class MainActivity extends ReactAppCompatActivity {
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
> +      getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN);
>     }
> }
> ```

现在发现，加了这行代码后，在我的项目中的webview中，靠下一点的输入框会被键盘挡住，无法自动调整页面布局，删掉后，在AndroidManifest.xml中加上android:windowSoftInputMode="stateUnchanged|adjustResize"貌似也解决了这个issue，并且不会出现键盘挡住输入框的问题。
