### ISSUE TITLE
ios，release包下的tab图标显示异常

### ISSUE THREAD

**Issue by danna88** [listenzz/hybrid-navigation#172]
使用的自定义的tab，ios下release包图标显示不对，debug包是好的
代码如下：

`<Image
          source={{
            uri: selected ? Image.resolveAssetSource(require('./sources/tab/myHover.png')) : Image.resolveAssetSource(require('./sources/tab/my.png')),
            width: 24,
            height: 24,
            scale: PixelRatio.get(),
          }}
          style={{paddingBottom: Platform.OS === 'android' ? 0 : 30}}
          resizeMode="center"
          fadeDuration={0}
        />`
什么原因呢？

**Comment by milkcha** [comment]
myHover 要有全尺寸的 1.5x 1x 2x 3x 4x

**Comment by danna88** [comment]
> myHover 要有全尺寸的 1.5x 1x 2x 3x 4x

必须全套才行？ 那我试试

**Comment by listenzz** [comment]
貌似是某个版本 rn 的问题
