### ISSUE TITLE
和 expo/react-native-unimodules 冲突

### ISSUE THREAD

**Issue by dautent** [listenzz/hybrid-navigation#180]
复现：
-  `react-native init MyApp`
-  集成 [RNNH](https://github.com/listenzz/react-native-navigation-hybrid/blob/master/doc/integration-react.md)
-  集成 [unimodule](https://docs.expo.io/bare/installing-unimodules/)
- 可以正常运行，控制台提示 `No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?`
- 只有iOS下unimodule集成失败，安卓正常

**Comment by dautent** [comment]
可复现代码
https://github.com/dautent/testprofile/tree/rnnh

**Comment by laogui** [comment]
```
import expo.modules.ReactActivityDelegateWrapper;
import com.reactnative.hybridnavigation.ReactAppCompatActivity;

public class MainActivity extends ReactAppCompatActivity {
    ...
    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
      return new ReactActivityDelegateWrapper(this, BuildConfig.IS_NEW_ARCHITECTURE_ENABLED, new DefaultReactActivityDelegate(
          this,
          getMainComponentName(),
          // If you opted-in for the New Architecture, we enable the Fabric Renderer.
          DefaultNewArchitectureEntryPoint.getFabricEnabled()));
    }
}
```

也想和expo集成，上面这个this报错不知道怎么处理，完全不懂java
