### ISSUE TITLE
Tab的页面不可以自定义header吗？

### ISSUE THREAD

**Issue by danna88** [listenzz/hybrid-navigation#183]
想隐藏自带的header，使用自定义的，结果崩溃

**Comment by listenzz** [comment]
你是怎么隐藏的呢？

**Comment by danna88** [comment]
设置这行代码：
static navigationItem = {
    topBarHidden: true, // 隐藏top bar
  };

**Comment by listenzz** [comment]
这应该不会有问题的。看看错误信息。

**Comment by danna88** [comment]
好，我再看下，感谢。
