### ISSUE TITLE
页面跳转 会先白一下

### ISSUE THREAD

**Issue by roycehe** [listenzz/hybrid-navigation#185]
![image](https://user-images.githubusercontent.com/12679536/113128317-4227b380-924c-11eb-9043-da2e99d8ac23.png)
![image](https://user-images.githubusercontent.com/12679536/113128353-4c49b200-924c-11eb-98f5-3450411b6fd7.png)

**Comment by listenzz** [comment]
这是由于 React 视图是异步加载的，跳转时，视图还没渲染好。当页面背景偏暗时，有几率能感到闪一下。 建议通过 screenBackgroundColor 来设置页面背景颜色。

**Comment by roycehe** [comment]
screenBackgroundColor是原生的api吗, 有没有办法渲染完成再跳转

**Comment by roycehe** [comment]
> 这是由于 React 视图是异步加载的，跳转时，视图还没渲染好。当页面背景偏暗时，有几率能感到闪一下。 建议通过 screenBackgroundColor 来设置页面背景颜色。
screenBackgroundColor是原生的api吗, 有没有办法渲染完成再跳转

**Comment by roycehe** [comment]
> 这是由于 React 视图是异步加载的，跳转时，视图还没渲染好。当页面背景偏暗时，有几率能感到闪一下。 建议通过 screenBackgroundColor 来设置页面背景颜色。
screenBackgroundColor是原生的api吗, 有没有办法渲染完成再跳转

**Comment by listenzz** [comment]
@roycehe screenBackgroundColor 是 hybrid-navigation 提供的，用来设置页面背景。

可以通过 Garden.setStyle 来全局设置，也可以通过 withNavigationItem 来为每个页面单独设置，把 screenBackgroundColor 设置成你页面的背景颜色，可以有效缓解会闪一下的问题。

**Comment by roycehe** [comment]
多谢
