### ISSUE TITLE
Garden 接口提供的API，与NavigationItem 数据结构相比，API方法不全

### ISSUE THREAD

**Issue by daselang** [listenzz/hybrid-navigation#191]
1.只有set方法，没有get方法返回最新的数据结构数据。导致在实例中想从navigationItem里面提取最新配置信息，再传递到下层页面时，无法获取最新的配置信息。
2.setLeftBarButtonItem与setRightBarButtonItem，只能set一个buttonItem,但是static的navigationItem可以配置多个buttonItems数组,导致在实例中不能动态set多个buttomItems或者update已有的buttomItems的配置.API方法不全。单个的setLeft/RightBarButtonItem方法，会导致static配置的多个buttonItems消失。
Garden提供的其他方法是否齐全，本人暂未关注。请作者大大检查一下。
很高兴结缘你的开源navigation库，很好用，很流畅。

**Comment by listenzz** [comment]
@daselang 

1. 通过 get 方法获取最新的数据，这个功能不考虑实现，可以通过其它方式达到同样的目的。

2. 由于我司没有动态更新多个 item 的需求，所以一直没留意到未提供同时设置多个 item 的 api。如果你有需求，可以考虑添加。

**Comment by daselang** [comment]
@listenzz 
1是有不少变通的方式，可以不加getter方法。
2.是需要的，API得和static的navigationItem的multi buttonItems []对应。因为我在静态配置多个right button Items时，显示的是两个右侧边bar button。但是在方法中动态设置时，只显示一个，另外一个就消失了。请加上setLeft/RightBarButtonItems吧。
