### ISSUE TITLE
Navigator.setInterceptor中需要更新下Extras类型定义

### ISSUE THREAD

**Issue by dppo** [listenzz/hybrid-navigation#192]
`static setInterceptor(interceptFn: NavigationInterceptor): void;`
`interface Extras {
    sceneId: string;
    index?: number;
}
`
`
export interface NavigationInterceptor {
    (action: string, extras: Extras): boolean | Promise<boolean>;
}
`
现在这个方法里好像没办法获取到目标页面了？  如果我要判断去某个页面需要验证登陆，现在怎么拦截？

**Comment by dppo** [comment]
另外，标题栏的字体粗细有调整的属性么？

**Comment by dppo** [comment]
{"from": "Tab4", "moduleName": "Setting", "options": {}, "props": {}, "sceneId": "FE5F9641-5780-4C61-AFB5-0E3A960E1AD1", "to": "Setting"}

已找到，应该是类型定义不对应的问题，能拿到返回数据

**Comment by listenzz** [comment]
@dppo 已更新 Extras 类型定义。标题加粗太难看，暂不提供实现。

**Comment by dppo** [comment]
> @dppo 已更新 Extras 类型定义。标题加粗太难看，暂不提供实现。

好的
