### ISSUE TITLE
请问如何缓存页面栈

### ISSUE THREAD

**Issue by weijintao92** [listenzz/hybrid-navigation#198]
我想将一个页面缓存在页面栈中

**Comment by listenzz** [comment]
这个需要自行实现。

编写 Navigator 插件

https://github.com/listenzz/hybrid-navigation/blob/master/ios/HybridNavigation/Navigator/HBDNavigator.h

https://github.com/listenzz/hybrid-navigation/blob/master/android/src/main/java/com/reactnative/hybridnavigation/navigator/Navigator.java
