### ISSUE TITLE
国际化，多语言支持，i18n-js 怎么做呢？

### ISSUE THREAD

**Issue by weijintao92** [listenzz/hybrid-navigation#206]
发现底部菜单栏，没法随着语言切换跟着变化。

**Comment by listenzz** [comment]
没做过国际化，没这方面的经验，请问通常是怎么做的呢？

**Comment by listenzz** [comment]
或者提供一个方法，可以动态更改底部菜单栏

**Comment by weijintao92** [comment]
刚刚又看了下文档。 动态配置的 updateTabBar不能修改底部菜单栏的文字呢

**Comment by weijintao92** [comment]
> 或者提供一个方法，可以动态更改底部菜单栏

就是没有找到这个方法呢

**Comment by listenzz** [comment]
现在是没有的

**Comment by weijintao92** [comment]
脑壳已然扣烂。。。

**Comment by weijintao92** [comment]
师兄你看什么时候，把这个  修改底部菜单栏`文字`的  加上呢！辛苦了

**Comment by listenzz** [comment]
我待会弄下，估计明天好

**Comment by weijintao92** [comment]
感动得快哭了。。。

**Comment by listenzz** [comment]
@weijintao92 添加了个叫 setTabItem 的方法，可以动态更改 tab text

**Comment by weijintao92** [comment]
感谢  ，我现在试一试

**Comment by weijintao92** [comment]
> @weijintao92 添加了个叫 setTabItem 的方法，可以动态更改 tab text

感谢作者，刚刚试了下，setTabItem 可以正常使用

**Comment by weijintao92** [comment]
但是感觉这里这样做不够优雅。现在，一次只能修改一个底部菜单栏的文字。希望可以传递一个数组。一次性修改所有的底部菜单栏。

**Comment by listenzz** [comment]
> 但是感觉这里这样做不够优雅。现在，一次只能修改一个底部菜单栏的文字。希望可以传递一个数组。一次性修改所有的底部菜单栏。

支持数组的，你仔细看看方法签名

**Comment by weijintao92** [comment]
好的！非常感谢作者！作者辛苦了，作者zhao 1w g p n
