### ISSUE TITLE
effect is not a function.

### ISSUE THREAD

**Issue by weijintao92** [listenzz/hybrid-navigation#207]
在项目启动时及页面跳转时回出现此错误
error message: TypeError: effect is not a function. (In 'effect()', 'effect' is "66e0de56-cb92-456a-b167-347938f451ea")
![image](https://user-images.githubusercontent.com/47779463/140287820-2591813f-1b54-417c-a8c1-49864e7f80ac.png)

**Comment by listenzz** [comment]
effect 是传递给 `useVisibleEffect` 的参数，它应该是一个函数，通常像如下这样使用

```ts
useVisibleEffect(useCallback(() => {
  return () => {
  }
}, []))
```

**Comment by weijintao92** [comment]
> effect 是传递给 `useVisibleEffect` 的参数，它应该是一个函数，通常像如下这样使用
> 
> ```ts
> useVisibleEffect(useCallback(() => {
>   return () => {
>   }
> }, []))
> ```

是我写错了，sorry
