### ISSUE TITLE
Navigator.setInterceptor((action, from, to, extras),  to字段返回undefined

### ISSUE THREAD

**Issue by dntzee** [listenzz/hybrid-navigation#219]
之前用 0.2版本的时候，Navigator.setInterceptor((action, from, to, extras)方法字段to返回的值正常，为注册的名称。

更新2.7.2版本后，to字段返回undefined。

因为需要使用这个字段统计路由跳转页面的名称，所以麻烦大神看下是什么原因呢，非常感谢！祝好

**Comment by listenzz** [comment]
现在方法签名变了，to 字段在 extras 里面，可能为 string、number(切换 tab 的时候)、undefined(pop、dismiss、hideModal 的时候)

```ts
// 设置导航拦截器
Navigator.setInterceptor((action, extras) => {
  console.info(`action:${action}`, extras)
  return false
})
```

**Comment by dntzee** [comment]
好的，谢谢
