### ISSUE TITLE
请问如何改变 showModal 默认的背景透明度？

### ISSUE THREAD

**Issue by xiaobo1234** [listenzz/hybrid-navigation#223]
如题，modal 自带的透明背景太黑了，想再淡一点儿。

已经试过设置 screenBackgroundColor，然而貌似只是在 modal 透明背景的基础上加了一层颜色，并不能改变 modal 本身的透明度。

**Comment by listenzz** [comment]
v2.8.0 之后，设置 modal 的背景为透明，然后设置 screenBackgroundColor

```js
export default withNavigationItem({
  forceTransparentDialogWindow: true,
  screenBackgroundColor: '#'
})(Modal)
```

**Comment by xiaobo1234** [comment]
@listenzz 
v2.8.0 之前的版本不能改吗？

**Comment by xiaobo1234** [comment]
> > @listenzz v2.8.0 之前的版本不能改吗？
> 
> 不可以

好的，谢谢
