### ISSUE TITLE
Reload后会初始化两次Stack的screen

### ISSUE THREAD

**Issue by NiuGuohui** [listenzz/hybrid-navigation#226]
新建了一个项目，运行后在控制台按R执行reload时会重复执行两次Home

控制台打印：
<img width="894" alt="image" src="https://user-images.githubusercontent.com/37471959/166896540-a3063678-b435-438c-b065-44327c4c39c5.png">

代码：
```
Garden.setStyle({ topBarStyle: BarStyleDarkContent });

ReactRegistry.startRegisterComponent();

ReactRegistry.registerComponent('Home', () => HomeScreen);
ReactRegistry.registerComponent('Detail', () => DetailScreen);

ReactRegistry.endRegisterComponent();

Navigator.setRoot({
  stack: {
    children: [{ screen: { moduleName: 'Home' } }],
  },
});
```

**Comment by listenzz** [comment]
是 Android 吗？第一个 Home 是 reload 之前存在的，它会在稍后销毁。

**Comment by NiuGuohui** [comment]
> 是 Android 吗？第一个 Home 是 reload 之前存在的，它会在稍后销毁。

是Android，建议后面有时间了还是修复一下吧:grin:

**Comment by listenzz** [comment]
> > 是 Android 吗？第一个 Home 是 reload 之前存在的，它会在稍后销毁。
> 
> 是Android，建议后面有时间了还是修复一下吧😁

好的呢
