### ISSUE TITLE
能否增加一个已有的原生项目相关的例子。

### ISSUE THREAD

**Issue by jamninetyfive** [listenzz/hybrid-navigation#231]
能否增加一个已有的原生项目相关的例子。

比如目前我的原生5个tab都是原生的，现在其中2个tab想换成RN页面。 -

**Comment by jamninetyfive** [comment]
文档https://todoit.tech/rn/hybrid-navigation/integration-native.html#%E5%88%9B%E5%BB%BA-rn-%E9%A1%B9%E7%9B%AE%E5%B9%B6%E9%9B%86%E6%88%90-navigation-hybrid

这里面 没有相关示例。

**Comment by listenzz** [comment]
这里有个例子 https://github.com/listenzz/react-native-toast-hybrid/tree/master/example，它有两个 tab，一个原生，一个 RN

需要对原有原生项目作一定改造，iOS 的控制器需要继承 HBDViewController, Android 需要使用 [AndroidNavigation](https://github.com/listenzz/AndroidNavigation) 改造成单 Activity 架构

**Comment by jamninetyfive** [comment]
谢谢回答，现在由于安卓项目已经是线上的项目，没办法说服进行全部改造，有最小兼容做法不。😂

**Comment by listenzz** [comment]
不需要所有页面都改造，只需要改造承载那 5 个 tab 的 Activity 即可，也就是一个 Activity + 原有 3 个 Fragment 的样子，同理，iOS 也不需要所有页面都继承 HBDViewController
