### ISSUE TITLE
navigationBarHiddenAndroid 参数在打开Modal时会发生抖动

### ISSUE THREAD

**Issue by NiuGuohui** [listenzz/hybrid-navigation#233]
在screen下，当showModal时，Android底部的虚拟导航会弹出来一下在自动隐藏，screen和modal都设置了navigationBarHiddenAndroid=true；
navigationBarHiddenAndroid 参数在Tab页面不生效；

**Comment by NiuGuohui** [comment]
尝试了自己在启动时强制隐藏systemUiVisibility，但是我们的库会在路由发生变化的时候重新设置systemUiVisibility

**Comment by listenzz** [comment]
截个图看看，是想要实现什么样的效果呢？

**Comment by NiuGuohui** [comment]
> 截个图看看，是想要实现什么样的效果呢？


https://user-images.githubusercontent.com/37471959/171323962-3e2beddb-e5d1-4da2-97e8-9d38343ddf57.mp4

注意看底部的虚拟按键，这两个页面都设置了navigationBarHiddenAndroid:true

**Comment by listenzz** [comment]
收到，确实是个问题

**Comment by NiuGuohui** [comment]
> 收到，确实是个问题

另外还有就是在Tab布局下这个参数不生效

**Comment by listenzz** [comment]
@NiuGuohui `navigationBarHiddenAndroid` 在 Tab 布局不生效的问题已经修复。

> 当showModal时，Android底部的虚拟导航会弹出来一下在自动隐藏

这是个兼容性问题，存在于 Android 9 及以下，无法解决。

可以变更 Modal 的实现方式来处理，使用 [hybrid-navigation-overlay](https://www.npmjs.com/package/hybrid-navigation-overlay) 来实现 Modal 即可。使用方式和 showModal, hideModal 基本一致

**Comment by listenzz** [comment]
@NiuGuohui 修改了 Modal 的实现方式，可以不用 [hybrid-navigation-overlay](https://www.npmjs.com/package/hybrid-navigation-overlay) 来实现 Modal 了，更新 hybrid-navigation 到 2.11.1 即可。

**Comment by NiuGuohui** [comment]
> @NiuGuohui 修改了 Modal 的实现方式，可以不用 [hybrid-navigation-overlay](https://www.npmjs.com/package/hybrid-navigation-overlay) 来实现 Modal 了，更新 hybrid-navigation 到 2.11.1 即可。

收到，我测试了一下，新Modal的实现基本上没啥问题啦，不过遮罩没有动画过渡了

**Comment by listenzz** [comment]
遮罩动画要自己做了，将 modal 背景设置为透明，增加一个 view 做背景

**Comment by NiuGuohui** [comment]
> 遮罩动画要自己做了，将 modal 背景设置为透明，增加一个 view 做背景

OK
