### ISSUE TITLE
react-native-safe-area-context问题

### ISSUE THREAD

**Issue by roycehe** [listenzz/hybrid-navigation#242]
![image](https://user-images.githubusercontent.com/12679536/196878789-562162ae-9d0a-4369-830e-df26f387e8f8.png)
useSafeAreaInsets拿不到值

**Comment by listenzz** [comment]
暂时可以使用 statusBarHeight() 来代替

**Comment by roycehe** [comment]
> 暂时可以使用 statusBarHeight() 来代替

从哪里导出呢

**Comment by listenzz** [comment]
import { statusBarHeight } from 'hybrid-navigation'

新版本支持

**Comment by listenzz** [comment]
2.14.0 已支持 react-native-safe-area-context
