### ISSUE TITLE
[Navigation] React Component 还没有注册完毕

### ISSUE THREAD

**Issue by ykxgithub** [listenzz/hybrid-navigation#251]
Android应用切到后台，隔一段时间再切回前台，容易触发这种报错导致应用闪退。

**Comment by listenzz** [comment]
有堆栈吗？

**Comment by ykxgithub** [comment]
![image](https://github.com/listenzz/hybrid-navigation/assets/13413218/5d3b0030-ff4f-4708-8f23-e7dedc1db5ec)

**Comment by listenzz** [comment]
这是 APP 冷重启页面重新创建，而此时 ReactNative 还没启动导致的问题。

通过以下步骤重现。

```sh
# 可能取得模拟器 root 权限
adb root
```

1. 启动 App，退到后台，输入以下命令杀死它

  ```sh
  adb shell am kill <你的应用包名>
  ```  
2. 点击 App 启动图标，试图让它回到前台，在 Logcat 上可以看到如下堆栈。

  ![image](https://github.com/listenzz/hybrid-navigation/assets/4386370/2c546804-4baf-4340-abb4-9ab6f1db068c)


**更新到 2.16.7，已修复此问题。**
