### ISSUE TITLE
编译错误: 找不到符号

### ISSUE THREAD

**Issue by boboxiaodd** [listenzz/hybrid-navigation#253]
https://github.com/listenzz/hybrid-navigation/blob/fb2a7f025378cfb0c4c159b0c970a71dae235345/android/src/main/java/com/reactnative/hybridnavigation/ReactStackFragment.java#L39

资源文件里面确实没有 nav_gone 这个动画

**Comment by listenzz** [comment]
这个文件在它的依赖 io.github.listenzz:AndroidNavigation 里面

```gradle
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.facebook.react:react-native:+'
    // api project(':navigation')
    api 'io.github.listenzz:AndroidNavigation:13.6.3'
}
```
