### ISSUE TITLE
topBarHidden 设置为true ,安卓没问题，iOS没有效果，想问事怎么回事

### ISSUE THREAD

**Issue by Mscynol** [listenzz/hybrid-navigation#256]
<img width="725" alt="image" src="https://github.com/listenzz/hybrid-navigation/assets/13941582/8b4f4058-8d9f-4bf4-8e5a-52473109043d">
<img width="715" alt="image" src="https://github.com/listenzz/hybrid-navigation/assets/13941582/4becb13d-e84f-4c12-9561-d11389e0c797">
<img width="764" alt="image" src="https://github.com/listenzz/hybrid-navigation/assets/13941582/5532d4d3-a2c6-4180-ae52-6d43eec337db">
还烦请大神看一下，是不是哪里我配置错了

**Comment by Mscynol** [comment]
<img width="779" alt="image" src="https://github.com/listenzz/hybrid-navigation/assets/13941582/0475bf2b-b8b5-4257-a515-31167a752cc9">
这是我的info 配置，第一张放错了，放的是你的demo的截图

**Comment by Mscynol** [comment]
iOS 显示图
<img width="327" alt="image" src="https://github.com/listenzz/hybrid-navigation/assets/13941582/c18ed009-11cd-4b9a-adc1-19dd0f2ef2b3">
android 显示图
<img width="420" alt="image" src="https://github.com/listenzz/hybrid-navigation/assets/13941582/70fdd1fe-6133-44fc-b743-ae2c742777d4">

**Comment by listenzz** [comment]
把你的 demo 直接发我吧

**Comment by Mscynol** [comment]
https://gitee.com/mscynol/easy.git

**Comment by listenzz** [comment]
事实上 topBar 已经移除，你看到的空白是 SafeAreaView 预留的，移除即可。

 另外需要 ScrollView 的 `contentInsetAdjustmentBehavior` 设置成 `never`，否则 ScrollView 上面会留白。

**Comment by Mscynol** [comment]
是的，IOS端但是我又发现一个问题就是如果topBarHidden: true
<img width="540" alt="image" src="https://github.com/listenzz/hybrid-navigation/assets/13941582/562f71a9-77ff-43ad-8329-ef09a16695ba">
这个勾选后，statusbar 也消失了，topBarHidden: true设置true以后也影响statusbar嘛，在IOS可以单独设置StatusBar的背景颜色不

**Comment by Mscynol** [comment]
hybrid-navigation是否以后也可以自动支持异形屏幕的支持，就跟safeareaview那样

**Comment by listenzz** [comment]
下面要设置为 YES, StatusBar 才可以根据页面配置变化
<img width="715" alt="image" src="https://github.com/listenzz/hybrid-navigation/assets/4386370/b54a5469-64eb-44e9-9584-0ea9a2876313">

在 iOS, StatusBar 的背景颜色是不可以设置的，只有前景色可以设置为黑或白

> hybrid-navigation是否以后也可以自动支持异形屏幕的支持，就跟safeareaview那样

在不隐藏 TopBar 的情况下，已经做了必要的支持，当隐藏 TopBar 时，默认留给开发者自己是配

**Comment by Mscynol** [comment]
好的，非常感谢

**Comment by khalisafkari** [comment]
I've been using GitHub for a long time and many of the maintainers too, sometimes they don't care about those who use the code, they even ignore the users who use the code, but I see you are very supportive and helpful. users in using your code, this is very rare, but you did it, I really hope one day every repo manager does what you do, I wish you every success @listenzz
