### ISSUE TITLE
一个 app，不同页面 如果使用了两个 tabbar 就无响应了。

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/hybrid-navigation#69]
比如打开一个 app，是一个 tabbar。 其中某个栏目以新窗口打开，该栏目底部也是个 tab，这时就出问题了，app 会无响应。

**Comment by listenzz** [comment]
是说 UITabBarController 的某个子控制器其实也是个 UITabBarController?

**Comment by yunuo-tech** [comment]
对，这种需求虽然少，但是也是会有这种需求的。

**Comment by listenzz** [comment]
最新版已无此问题
